### PR TITLE
Hotfix/copy tweaks

### PR DESCRIPTION
**Pull request by stringfellow**
@geojayuu I named this branch rather unambitiously, so there are actually a few field tweaks and bug fixes in here too.

### CODE REVIEW

**Comment by geojayuu** [comment]
I checked out the branch and tested the form. 

ie.
git fetch origin
git checkout -b hotfix/copy-tweaks origin/hotfix/copy-tweaks
git merge master

Did I also need to do something with those patch files?

I think there are some issues with some of the fields I added previously - The form wouldn’t submit as some required fields were missing:

Can I submit changes to fix to hot fix/copy tweaks directly or would you prefer me to Merge hotfix/copy-tweaks and then fix these issues in a subsequent branch?

**Comment by geojayuu** [comment]
This looks fine - I added another commit of minor field changes (including a some PEP8 fixes).

**Comment by stringfellow** [comment]
:+1:

**Comment by geojayuu** [comment]
:+1:

**Comment by geojayuu** [comment]
Closed by mistake.

**Comment by geojayuu** [comment]
:+1:

**Pull request merged**
